// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignTagsToProject(arg1, arg2) {
  return window['go']['main']['App']['AssignTagsToProject'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function CreateTimeBlock(arg1) {
  return window['go']['main']['App']['CreateTimeBlock'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTimeBlock(arg1) {
  return window['go']['main']['App']['DeleteTimeBlock'](arg1);
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetProjectByID(arg1) {
  return window['go']['main']['App']['GetProjectByID'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTagByID(arg1) {
  return window['go']['main']['App']['GetTagByID'](arg1);
}

export function GetTagsByProjectID(arg1) {
  return window['go']['main']['App']['GetTagsByProjectID'](arg1);
}

export function GetTimeBlocksByDate(arg1) {
  return window['go']['main']['App']['GetTimeBlocksByDate'](arg1);
}

export function GetTimeBlocksByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetTimeBlocksByDateRange'](arg1, arg2);
}

export function StopRunningTimeBlock(arg1) {
  return window['go']['main']['App']['StopRunningTimeBlock'](arg1);
}

export function StopTimeBlockWithDuration(arg1, arg2) {
  return window['go']['main']['App']['StopTimeBlockWithDuration'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTag(arg1, arg2) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2);
}

export function UpdateTimeBlock(arg1, arg2) {
  return window['go']['main']['App']['UpdateTimeBlock'](arg1, arg2);
}
